# Generated by Django 6.0.4 on 2026-05-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Remaining',
            field=models.FloatField(default=0),
        ),
    ]
