# Generated by Django 6.0.4 on 2026-05-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_app', '0002_customer_total_alter_customer_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='Unpaid', max_length=100),
        ),
    ]
