# Generated by Django 6.0.4 on 2026-05-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_app', '0003_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=100),
        ),
    ]
